### ISSUE TITLE
Create a new package with an updated Version

### ISSUE THREAD

**Issue by brahernandes** [Jwaegebaert/react-script-editor#1]
Hi, can you please create a new package with the latest version of the project (1.20.0)?
I need the latest version with the feature to deploy to a modern team site, for that, the ScriptEditorWebPart.manifest.json must be edited setting the "requiresCustomScript" to false.
I have tried to build this solution for almost a week but no sucess :(

Thanks in advance, and a merry christmas.

**Comment by Jwaegebaert** [comment]
Hey @brahernandes, I've update the sppkg to version 1.0.20 as requested 😄 
In the manifest, I've disabled `requiresCustomScript` before building the package.

Happy holidays!
